### ISSUE TITLE
UI Enhancements for Mobile Responsiveness and Improvements 

### ISSUE THREAD

**Issue by dhextras** [JasonBoyett/project-iris#10]
#### What Needs To Change:

> **Known Issues:**
    - Lack of mobile responsiveness, particularly for smaller devices.
    - Oversized elements like the logo and content causing visual overload on the home page.

> **Exercise Page Modifications:**
    - Make it scrollable in `greenDots` to facilitate reading longer content.
    - Fix alignment issue in `flashwords` where text wrapping on smaller screens doesn't center correctly.
    - Address the disappearing top input bar in the calculator after displaying the number, specifically in mobile view.
    - Implement simple red-green highlighting or sound cues for right and wrong answers in exercises and speed tests.
    - Make the entire answer area clickable for testing instead of requiring specific movement to select an answer tag (A, B, C...).
    - Create a button in the `/next` page to return to the `/nav` page.

> **Overall Mobile Updates:**
    - Improve mobile UI appeal and functionality across exercises.
    - Resolve glitching counter button issues occurring on both mobile and desktop.
    - Enhance the setting and navigation bar pages for better centering and improved layout.

> **Additional Tasks:**
    - Implement the shared issue template for consistency and easy reference.

#### Definition of Done:

- **Responsive Design:**
    - [x] UI adjusts effectively for smaller mobile screens.
    - [ ] #16

- **Exercise Page Modifications:**
    - [x] Green dots made scrollable for easy reading of longer content.
    - [ ] #15
    - [x] Rectify disappearing top input bar in the calculator, specifically in mobile view.
    - [x] Implement visual cues (color highlights) or simple sounds for correct and incorrect answers.
    - [x] Make entire answer area clickable for ease of testing navigation.

- **Overall Mobile Updates:**
    - [x] Improve UI appeal and functionality, resolving glitching counter button issues.
    - [x] Enhance layout and centering of setting and navigation bar pages for a more polished appearance.

- **Additional Tasks:**
    - [ ] #17

#### Expected Changes:

-  Ensure responsiveness, especially on smaller devices.
-  Optimize visual elements, reducing oversized content for better user experience.
-  Enable scrollable green dots for extended reading in exercises.
-  Correct alignment issues in flashwords for text wrapping on smaller screens.
-  Fix disappearing top input bar in the calculator, specifically in mobile view.
-  Implement visual cues (color or sound) for right and wrong answers.
-  Make entire answer areas clickable for easier navigation in testing.
-  Resolve glitching counter button issues across mobile and desktop views.
-  Improve the layout and centering of setting and navigation bar pages.
-  Apply the shared issue template for consistent formatting and documentation.

> Note: Gpt Touched for better wording :D

**Comment by JasonBoyett** [comment]
Overall I think these are good changes except for two of them. 

- On the green dot exercise, you are not meant to read the text, just to stare at the green dot while keeping the text in your peripheral vision so making it scrollable would be counterproductive. 
- The speed test and the matching exercises intentionally do not give feedback. Because this is meant for an academic study we want to eliminate variables and we considered someone's stress response to seeing a red flash when they got a wrong answer to be a variable. I agree it would be better for UX to give immediate feedback but it could possibly skew the data are collecting. Maybe if the user is not a study subject they get the feedback and if they are they do not then I could approve that feature.

**Comment by JasonBoyett** [comment]
I solved most of the issues brought up in this issue and pushed a few more into their own issues to be picked up later.

**Comment by dhextras** [comment]
> Overall I think these are good changes except for two of them. 
> 
> - On the green dot exercise, you are not meant to read the text, just to stare at the green dot while keeping the text in your peripheral vision so making it scrollable would be counterproductive. 
> - The speed test and the matching exercises intentionally do not give feedback. Because this is meant for an academic study we want to eliminate variables and we considered someone's stress response to seeing a red flash when they got a wrong answer to be a variable. I agree it would be better for UX to give immediate feedback but it could possibly skew the data are collecting. Maybe if the user is not a study subject they get the feedback and if they are they do not then I could approve that feature.

Ohh i see then its not an good idea to give imediate feedback. K got it. So implemeting instruction would be really neded.

Any way other then those two it seems u already finished up other things. Ill take a look into it later on and let u know my thoughts
