### ISSUE TITLE
Update URL In About Section

### ISSUE THREAD

**Issue by statulr** [JasonBoyett/project-iris#11]
Self Explanatory

**Comment by JasonBoyett** [comment]
I just updated it. Mind checking if it works for you now?

**Comment by statulr** [comment]
URL isn't updated for me.

**Comment by JasonBoyett** [comment]
mind shooting me a message on Discord so we can troubleshoot this? JasonB#1857

**Comment by statulr** [comment]
@JasonBoyett Yup!

**Comment by JasonBoyett** [comment]
Thanks for pointing this out. I got that fixed.
