### ISSUE TITLE
Can't Sign Up using GitHub

### ISSUE THREAD

**Issue by statulr** [JasonBoyett/project-iris#12]
<img width="1106" alt="Screenshot 2023-11-14 at 12 19 58 PM" src="https://github.com/JasonBoyett/project-iris/assets/122219240/555162e1-a43f-455d-934b-9e7ed7c30b3c">

**Comment by JasonBoyett** [comment]
is this on the main sight or a local build?

**Comment by statulr** [comment]
So sorry for late response, this is on main sight.
